# Generated by Django 5.2 on 2025-05-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_basicuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='fcm',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token', null=True),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
