# Generated by Django 5.2 on 2025-05-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_basicuser_fcm_alter_basicuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
