# Generated by Django 5.2 on 2025-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_basicuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'Français'), ('arabic', 'العربية')], default='english', max_length=10),
        ),
    ]
