# Generated by Django 5.2 on 2025-05-06 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_friends', to='location_sharing.userlocation')),
            ],
            options={
                'unique_together': {('user_location', 'friend')},
            },
        ),
    ]
