# Generated by Django 5.2 on 2025-05-07 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sharing', '0002_selectedfriends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedFriends',
            new_name='SelectedFriend',
        ),
        migrations.AlterModelOptions(
            name='selectedfriend',
            options={'verbose_name': 'Selected Friend', 'verbose_name_plural': 'Selected Friends'},
        ),
        migrations.RenameField(
            model_name='locationsharing',
            old_name='shared_with',
            new_name='friend',
        ),
        migrations.AddField(
            model_name='locationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='locationsharing',
            unique_together={('user', 'friend')},
        ),
    ]
