# Generated by Django 5.2 on 2025-06-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missing', '0011_alter_missingperson_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='Confidence percentage (0-100)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('algorithm_used', models.CharField(default='face_recognition', max_length=100)),
                ('face_distance', models.FloatField(blank=True, null=True)),
                ('processing_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches_as_match', to='missing.missingperson')),
                ('original_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches_as_original', to='missing.missingperson')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'unique_together': {('original_case', 'matched_case')},
            },
        ),
    ]
