# Generated by Django 5.2 on 2025-07-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimatch',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='aimatch',
            name='algorithm_used',
        ),
        migrations.RemoveField(
            model_name='aimatch',
            name='reviewed_by',
        ),
    ]
