# Generated by Django 5.2 on 2025-04-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('report_status', models.CharField(choices=[('new', 'new'), ('verified', 'verified'), ('false', 'false'), ('unverified', 'unverified')], default='new', max_length=10)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='missing.missingperson')),
            ],
        ),
    ]
