# Generated by Django 5.2 on 2025-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('photo', models.ImageField(upload_to='missing_photos/')),
                ('description', models.TextField(blank=True)),
                ('last_seen_date', models.DateField()),
                ('last_seen_location', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('found', 'found'), ('under_investigation', 'under_investigation')], default='searching', max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
