# Generated by Django 5.2 on 2025-04-25 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(upload_to='cases_photos/'),
        ),
    ]
