# Generated by Django 5.2 on 2025-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0003_alter_missingperson_age_alter_missingperson_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen_location',
            field=models.CharField(max_length=200),
        ),
    ]
