# Generated by Django 5.2 on 2025-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0004_alter_missingperson_last_seen_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'found'), ('Investigating', 'under_investigation')], default='searching', max_length=50),
        ),
    ]
