# Generated by Django 5.2 on 2025-05-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0005_alter_missingperson_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='submission_status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'found'), ('Investigating', 'under_investigation')], default='missing', max_length=50),
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='missing.missingperson')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
