# Generated by Django 5.2 on 2025-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0006_missingperson_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'found'), ('under_investigation', 'Investigating')], default='missing', max_length=50),
        ),
    ]
