# Generated by Django 5.2 on 2025-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0007_alter_missingperson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('under_investigation', 'Investigating')], default='missing', max_length=50),
        ),
    ]
