# Generated by Django 5.2 on 2025-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0008_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
