# Generated by Django 5.2 on 2025-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0009_missingperson_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='contact_phone',
            field=models.CharField(default='12345678', max_length=20),
        ),
    ]
