# Generated by Django 5.2 on 2025-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0010_alter_missingperson_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
