# Generated by Django 5.2 on 2025-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0013_alter_missingperson_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True),
        ),
    ]
