# Generated by Django 5.2 on 2025-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_content_type_notification_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Notification'), ('missing_person', 'Missing Person Notification'), ('report', 'Report Notification'), ('location_request', 'Location Request'), ('location_response', 'Location Response')], default='system', max_length=50),
        ),
    ]
