# Generated by Django 5.2 on 2025-05-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Notification'), ('missing_person', 'Missing Person Notification'), ('report', 'Report Notification'), ('location_request', 'Location Request'), ('location_response', 'Location Response'), ('case_update', 'Case Update'), ('location_alert', 'Location Alert')], default='system', max_length=50),
        ),
    ]
